/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A reusable, pre-initialized sandbox. */
export declare class Sandbox {
  /**
   * Create a sandbox and pre-initialize platform policy state off the event
   * loop.
   */
  static build(options?: SandboxOptions | undefined | null): Promise<Sandbox>
  /**
   * Spawn `command` (with `args`) inside this sandbox. stdio is inherited
   * from the parent process; every other parent file descriptor or handle
   * is kept out of the child.
   */
  spawn(command: string, args?: Array<string> | undefined | null, options?: SandboxSpawnOptions | undefined | null): SandboxChild
}

/** Handle to a spawned, sandboxed child process. */
export declare class SandboxChild {
  /** OS process id of the child. */
  get pid(): number
  /**
   * Wait for the child to exit. Resolves with its [`ExitResult`]. Calling
   * `wait()` while another wait is active, or after one succeeds, rejects. A
   * failed wait may be retried.
   */
  wait(): Promise<ExitResult>
  /**
   * Kill the child immediately. Best-effort: if `wait()` is already in
   * flight, killing falls back to an OS signal on Unix and is unsupported on
   * Windows (see the package README).
   */
  kill(): void
}

/** The result of awaiting a child's exit. */
export interface ExitResult {
  /** Exit code, or `null` if the process was terminated by a signal (Unix). */
  code?: number
  /** Terminating signal number (Unix only); `null` otherwise. */
  signal?: number
  /** `true` iff the process exited cleanly with code 0. */
  success: boolean
}

export interface FsAccess {
  /**
   * `"read-allow"` | `"read-deny"` | `"write-allow"` | `"write-deny"` |
   * `"execute-allow"` | `"execute-deny"`.
   */
  kind: FsAccessKind
  /** Path the rule covers recursively. */
  path: string
}

export type FsAccessKind =  'read-allow'|
'read-deny'|
'write-allow'|
'write-deny'|
'execute-allow'|
'execute-deny';

/**
 * Linux-only IPC confinement level for the child: `"strict"` | `"relaxed"`.
 * Mirrors `guardrail::IpcPolicy`. Ignored on macOS and Windows (see
 * `linuxIpc` on the options objects).
 */
export type IpcPolicy =  'strict'|
'relaxed';

/**
 * Network confinement level for the child: `"deny"` | `"outbound-only"` |
 * `"full"`. Mirrors `guardrail::NetworkPolicy`; the string values are the
 * ones typed by the JS caller.
 */
export type NetworkPolicy =  'deny'|
'outbound-only'|
'full';

/**
 * Probe whether this machine appears to support sandbox confinement. Throws
 * when a required kernel/OS capability cannot be probed. On Linux, Landlock
 * enforcement is verified, but the seccomp probe only checks whether the
 * kernel reports the `Trap` action; it cannot prove that an ambient sandbox
 * will permit installing the filter. Actual spawning remains authoritative
 * and fails closed, so calling this first is optional. Policy-specific checks,
 * such as the Landlock ABI v4 requirement for outbound-only networking with
 * relaxed IPC, run when `Sandbox.build()` or one-shot `spawn()` constructs the
 * backend.
 */
export declare function probeSupport(): void

/**
 * Sandbox policy. All fields optional; omitting everything
 * yields the maximally restrictive default (no fs, no network, strict Linux
 * IPC, empty environment).
 */
export interface SandboxOptions {
  /**
   * Filesystem rules, in declaration order. Later matching rules override
   * earlier rules for the same right. Note: `"execute-allow"` does NOT imply
   * read — add a `"read-allow"` rule for the binary and its libraries too.
   */
  fs?: Array<FsAccess>
  /** Network confinement level; `"deny"` (default) if omitted. */
  network?: NetworkPolicy
  /**
   * Linux-only IPC confinement level; `"strict"` (default) if omitted.
   * Ignored on macOS and Windows.
   */
  linuxIpc?: IpcPolicy
  /**
   * Linux-only user-namespace policy; `"deny"` (default) if omitted.
   * Ignored on macOS and Windows. Set `"allow"` only when the child runs
   * its own nested sandbox (Chromium/Electron, bubblewrap, rootless
   * containers): it re-enables user-namespace creation and the mount
   * machinery such a sandbox needs.
   */
  linuxUserNamespaces?: UserNamespacePolicy
  /**
   * Address-space cap in megabytes. Windows: aggregate Job Object budget
   * for the whole tree; Linux/macOS: per-process `RLIMIT_AS`, inherited by
   * descendants but not aggregated across forks.
   */
  memoryLimitMb?: number
  /**
   * CPU-time cap in seconds. Windows: aggregate per-job budget;
   * Linux/macOS: per-process `RLIMIT_CPU`, not aggregated across forks.
   */
  cpuTimeLimitSecs?: number
  /**
   * Maximum number of processes. Windows: active processes in the Job
   * Object; Linux/macOS: `RLIMIT_NPROC`, which counts all processes (on
   * Linux, also threads) of the real user ID system-wide and is not
   * enforced for privileged users.
   */
  maxProcesses?: number
  /**
   * The ONLY environment variables the child sees (inherited env is cleared).
   * On Windows, a bare program name resolves against this env's `PATH` only,
   * whose non-empty entries must be absolute. Spawning e.g. `cmd` requires
   * listing the expanded system directory, e.g. `C:\Windows\System32`.
   */
  env?: Record<string, string>
  /**
   * macOS-only trusted Seatbelt policy imports; ignored on other platforms.
   * Imported `allow` rules can grant access absent from `fs` and `network`,
   * including filesystem paths not listed in `fs`. Review profiles and their
   * transitive imports, and keep them outside child-writable paths.
   */
  darwinSandboxProfiles?: Array<string>
  /** Windows-only AppContainer cache namespace; ignored on other platforms. */
  windowsCacheNamespace?: string
}

/** Per-spawn launch options for a reusable [`Sandbox`]. */
export interface SandboxSpawnOptions {
  /** Working directory for the child. Defaults to the parent's cwd. */
  cwd?: string
}

/**
 * Spawn `command` (with `args`) confined by `options`. stdio is inherited from
 * the parent process; every other parent file descriptor or handle is kept
 * out of the child. Returns a handle to await or kill the child.
 */
export declare function spawn(command: string, args?: Array<string> | undefined | null, options?: SpawnOptions | undefined | null): SandboxChild

/**
 * One-shot sandbox policy + launch options. All fields optional; omitting
 * everything yields the maximally restrictive default.
 */
export interface SpawnOptions {
  /**
   * Filesystem rules, in declaration order. Later matching rules override
   * earlier rules for the same right. Note: `"execute-allow"` does NOT imply
   * read — add a `"read-allow"` rule for the binary and its libraries too.
   */
  fs?: Array<FsAccess>
  /** Network confinement level; `"deny"` (default) if omitted. */
  network?: NetworkPolicy
  /**
   * Linux-only IPC confinement level; `"strict"` (default) if omitted.
   * Ignored on macOS and Windows.
   */
  linuxIpc?: IpcPolicy
  /**
   * Linux-only user-namespace policy; `"deny"` (default) if omitted.
   * Ignored on macOS and Windows. Set `"allow"` only when the child runs
   * its own nested sandbox (Chromium/Electron, bubblewrap, rootless
   * containers): it re-enables user-namespace creation and the mount
   * machinery such a sandbox needs.
   */
  linuxUserNamespaces?: UserNamespacePolicy
  /**
   * Address-space cap in megabytes. Windows: aggregate Job Object budget
   * for the whole tree; Linux/macOS: per-process `RLIMIT_AS`, inherited by
   * descendants but not aggregated across forks.
   */
  memoryLimitMb?: number
  /**
   * CPU-time cap in seconds. Windows: aggregate per-job budget;
   * Linux/macOS: per-process `RLIMIT_CPU`, not aggregated across forks.
   */
  cpuTimeLimitSecs?: number
  /**
   * Maximum number of processes. Windows: active processes in the Job
   * Object; Linux/macOS: `RLIMIT_NPROC`, which counts all processes (on
   * Linux, also threads) of the real user ID system-wide and is not
   * enforced for privileged users.
   */
  maxProcesses?: number
  /**
   * The ONLY environment variables the child sees (inherited env is cleared).
   * On Windows, a bare program name resolves against this env's `PATH` only,
   * whose non-empty entries must be absolute. Spawning e.g. `cmd` requires
   * listing the expanded system directory, e.g. `C:\Windows\System32`.
   */
  env?: Record<string, string>
  /**
   * macOS-only trusted Seatbelt policy imports; ignored on other platforms.
   * Imported `allow` rules can grant access absent from `fs` and `network`,
   * including filesystem paths not listed in `fs`. Review profiles and their
   * transitive imports, and keep them outside child-writable paths.
   */
  darwinSandboxProfiles?: Array<string>
  /** Windows-only AppContainer cache namespace; ignored on other platforms. */
  windowsCacheNamespace?: string
  /** Working directory for the child. Defaults to the parent's cwd. */
  cwd?: string
}

/**
 * Linux-only user-namespace policy for the child: `"deny"` | `"allow"`.
 * Mirrors `guardrail::UserNamespacePolicy`. Ignored on macOS and Windows
 * (see `linuxUserNamespaces` on the options objects).
 */
export type UserNamespacePolicy =  'deny'|
'allow';
