/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Handle to a spawned, sandboxed child process. */
export declare class SandboxChild {
  /** OS process id of the child. */
  get pid(): number
  /**
   * Wait for the child to exit. Resolves with its [`ExitResult`]. Calling
   * `wait()` more than once rejects.
   */
  wait(): Promise<ExitResult>
  /**
   * Kill the child immediately. Best-effort: if `wait()` is already in
   * flight, killing falls back to an OS signal on Unix and is unsupported on
   * Windows (see the package README).
   */
  kill(): void
}

/** The result of awaiting a child's exit. */
export interface ExitResult {
  /** Exit code, or `null` if the process was terminated by a signal (Unix). */
  code?: number
  /** Terminating signal number (Unix only); `null` otherwise. */
  signal?: number
  /** `true` iff the process exited cleanly with code 0. */
  success: boolean
  /**
   * Best-effort diagnostic when the run failed; `null` on success or when the
   * failure could not be attributed to a policy.
   */
  violation?: Violation
}

export interface FsAccess {
  /** `"read"` | `"write"` | `"execute"`. */
  kind: FsAccessKind
  /** Path granted access (recursive). */
  path: string
}

export type FsAccessKind =  'read'|
'write'|
'execute';

/**
 * IPC confinement level for the child: `"strict"` | `"relaxed"`. Mirrors
 * `guardrail_core::IpcPolicy`.
 */
export type IpcPolicy =  'strict'|
'relaxed';

/**
 * Network confinement level for the child: `"deny"` | `"outbound-only"` |
 * `"full"`. Mirrors `guardrail_core::NetworkPolicy`; the string values are the
 * ones typed by the JS caller.
 */
export type NetworkPolicy =  'deny'|
'outbound-only'|
'full';

/**
 * Spawn `command` (with `args`) confined by `options`. stdio is inherited from
 * the parent process. Returns a handle to await or kill the child.
 */
export declare function spawn(command: string, args?: Array<string> | undefined | null, options?: SpawnOptions | undefined | null): SandboxChild

/**
 * Sandbox policy + launch options. All fields optional; omitting everything
 * yields the maximally restrictive default (no fs, no network, strict IPC,
 * empty environment).
 */
export interface SpawnOptions {
  /**
   * Filesystem grants, in declaration order. Grants are applied in the order
   * given. Note: `"execute"` does NOT imply read — add a `"read"` grant for
   * the binary and its libraries too.
   */
  fs?: Array<FsAccess>
  /** Network confinement level; `"deny"` (default) if omitted. */
  network?: NetworkPolicy
  /** IPC confinement level; `"strict"` (default) if omitted. */
  ipc?: IpcPolicy
  /** Address-space cap in megabytes. */
  memoryLimitMb?: number
  /** CPU-time cap in seconds. */
  cpuTimeLimitSecs?: number
  /** Maximum number of processes/threads. */
  maxProcesses?: number
  /** The ONLY environment variables the child sees (inherited env is cleared). */
  env?: Record<string, string>
  /** macOS-only Seatbelt `.sb` profile paths; ignored on other platforms. */
  darwinSandboxProfiles?: Array<string>
  /** Working directory for the child. Defaults to the parent's cwd. */
  cwd?: string
}

/** A heuristic explanation of a suspected policy violation. */
export interface Violation {
  /** The suspected category. */
  kind: ViolationKind
  /** One-line human summary. */
  summary: string
  /** Copy-pasteable next steps (which option to add to loosen the policy). */
  suggestions: Array<string>
}

/**
 * The category of a suspected policy violation: `"seccomp"` | `"resource-limit"`
 * | `"filesystem"` | `"unknown"`. Mirrors `guardrail_core::ViolationKind`.
 */
export type ViolationKind =  'seccomp'|
'resource-limit'|
'filesystem'|
'unknown';
